### ISSUE TITLE
Return content unmodified for widget to handle

### ISSUE THREAD

**Issue by rachelslurs** [PicoNetworks/wordpress-plugin#154]
To hopefully prevent more plugin conflicts, we can move the article chopping to the widget. I propose I return the entire content.

@hoppy-kamper would it be helpful to have a boolean in the `Pico` object saying whether the read more is being set explicitly by the publisher? Or is it better for you to determine?

Currently I'm seeing it returns a `<span id="more-2516"></span>` where the number is the post id, but I'm wondering if that's something that can be changed via plugin/theme.

A quick skim of this suggests I should probably tell you what the more tag looks like: https://codex.wordpress.org/Customizing_the_Read_More

**Comment by hoppy-kamper** [comment]
Yeah that sounds great. If the `Pico` object declares the id we will use to set the break then we should be in good shape.

Will the plugin continue to wrap the post with a `Pico` tag, or will the widget be responsible for that as well?

**Comment by rachelslurs** [comment]
I'm thinking we might still need to wrap the pico tag for the widget to target, right?

**Comment by rachelslurs** [comment]
Unless we also tell the react widget what the content will be contained by (a selector, the way we will do for the break)

**Comment by hoppy-kamper** [comment]
Yea, it would be ideal to still wrap the content with a Pico tag. If we find there are still issues with article manipulation we can consider trying to handle that as well, but baby steps makes sense for this simple trial.

**Comment by rachelslurs** [comment]
For later, came across this for targeting the post body: https://developer.wordpress.org/reference/functions/post_class/
