### ISSUE TITLE
Post tag being ignored by Pico

### ISSUE THREAD

**Issue by nychen** [PicoNetworks/wordpress-plugin#168]
Zendesk ticket: https://pico.zendesk.com/agent/tickets/1487

Block Club Chicago has a subscription meter for all content tagged with `locked`, but it seems that not all of those posts are getting counted by Pico.

@hoppy-kamper thinks it could be related to https://github.com/PicoNetworks/wordpress-plugin/issues/167

**Comment by rachelslurs** [comment]
![screen shot 2018-11-27 at 11 49 50 am](https://user-images.githubusercontent.com/1870406/49097583-0a9f3b80-f23b-11e8-86e8-27e627f021d8.png)

The tags and categories appear to be sent properly from BCC. The only thing that would be nice is to offer the prompt debug info on every loader call and not just when the prompt is due.

**Comment by rachelslurs** [comment]
Added ticket https://github.com/PicoNetworks/API/issues/1170
