### ISSUE TITLE
Set up an updater class that connects our GitHub releases to the WordPress plugin to notify when there are updates

### ISSUE THREAD

**Issue by rachelslurs** [PicoNetworks/wordpress-plugin#52]
Here's the how to: https://code.tutsplus.com/tutorials/distributing-your-plugins-in-github-with-automatic-updates--wp-34817

And an example of a plugin that does the same thing: https://github.com/afragen/github-updater

-----------

If we want to set up automatic background updates, Scott found this plugin that could be a guide (includes email alerts, too!) https://wordpress.org/plugins/automatic-plugin-updates

**Comment by hoppy-kamper** [comment]
The main goals of this task are to:
* Increase visibility in the publisher dashboard as to the status of available plugin updates
* Implement a simple workflow to update the Wordpress Plugin from within the wp-admin console.

**Comment by hoppy-kamper** [comment]
While exploring the existing code, I noticed that implementing multiple domains for publishers broke the wordpress health check. Fixing as part of this task since the implementation will be similar as version checking for the publisher app.

**Comment by hoppy-kamper** [comment]
Ended up using this module to handle the update checking for us (https://github.com/YahnisElsts/plugin-update-checker). Seems like it's working so far, but have some tweaks to ensure the Release Notes and github api request throttling works as expected.

<img width="637" alt="screen shot 2018-03-06 at 4 24 41 pm" src="https://user-images.githubusercontent.com/1940191/37064699-3bccb18a-215b-11e8-922f-4b5a696fc339.png">
