### ISSUE TITLE
Non-default themes not allowing <pico>content</pico> to exist

### ISSUE THREAD

**Issue by rachelslurs** [PicoNetworks/wordpress-plugin#67]
This might be an issue where the theme is modifying the content filter that we are relying on to create our snippet with.

Observed in themes like HitMag and ColorMag. Growler doesn't appear on non-article pages, but widget seems to work in articles.

![image](https://user-images.githubusercontent.com/3238214/34908803-e7005460-f863-11e7-8c35-dc24b552d123.png)

**Comment by seans887** [comment]
Tied to fate of #69

**Comment by hoppy-kamper** [comment]
Fixed by https://github.com/PicoNetworks/wordpress-plugin/pull/75
